/* tslint:disable */
/* eslint-disable */
/**
 * BookCycle API
 * API documentation for the BookCycle project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ApiUploadPost200Response
 */
export interface ApiUploadPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiUploadPost200Response
     */
    'imageUrl'?: string;
}
/**
 * 
 * @export
 * @interface ApiUploadPost400Response
 */
export interface ApiUploadPost400Response {
    /**
     * 
     * @type {string}
     * @memberof ApiUploadPost400Response
     */
    'error'?: string;
}
/**
 * 
 * @export
 * @interface ApiUploadPost500Response
 */
export interface ApiUploadPost500Response {
    /**
     * 
     * @type {string}
     * @memberof ApiUploadPost500Response
     */
    'error'?: string;
}
/**
 * 
 * @export
 * @interface BookDetailsResponse
 */
export interface BookDetailsResponse {
    /**
     * 
     * @type {number}
     * @memberof BookDetailsResponse
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof BookDetailsResponse
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof BookDetailsResponse
     */
    'author': string;
    /**
     * 
     * @type {string}
     * @memberof BookDetailsResponse
     */
    'image'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof BookDetailsResponse
     */
    'images'?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof BookDetailsResponse
     */
    'description': string;
    /**
     * 
     * @type {number}
     * @memberof BookDetailsResponse
     */
    'price': number;
    /**
     * 
     * @type {number}
     * @memberof BookDetailsResponse
     */
    'pages'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BookDetailsResponse
     */
    'discount'?: number;
    /**
     * 
     * @type {BookTypeEnum}
     * @memberof BookDetailsResponse
     */
    'categoryName': BookTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof BookDetailsResponse
     */
    'edition'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BookDetailsResponse
     */
    'year'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BookDetailsResponse
     */
    'dateCreated'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BookDetailsResponse
     */
    'numReviews'?: number | null;
}


/**
 * 
 * @export
 * @interface BookResponse
 */
export interface BookResponse {
    /**
     * 
     * @type {number}
     * @memberof BookResponse
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof BookResponse
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof BookResponse
     */
    'author': string;
    /**
     * 
     * @type {string}
     * @memberof BookResponse
     */
    'image'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BookResponse
     */
    'description': string;
    /**
     * 
     * @type {number}
     * @memberof BookResponse
     */
    'price': number;
    /**
     * 
     * @type {number}
     * @memberof BookResponse
     */
    'discount'?: number;
    /**
     * 
     * @type {BookTypeEnum}
     * @memberof BookResponse
     */
    'categoryName': BookTypeEnum;
}


/**
 * Enum for book categories
 * @export
 * @enum {string}
 */

export const BookTypeEnum = {
    Fiction: 'fiction',
    Romance: 'romance',
    Children: 'children',
    Fantasy: 'fantasy',
    Mystery: 'mystery',
    Business: 'business',
    Personal: 'personal',
    All: 'all'
} as const;

export type BookTypeEnum = typeof BookTypeEnum[keyof typeof BookTypeEnum];



/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Fetches book\'s details from the database.
         * @summary Get book\'s details
         * @param {number} id ID of the book
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBookDetailsIdGet: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiBookDetailsIdGet', 'id', id)
            const localVarPath = `/api/book/details/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Fetches books on sale from the database.
         * @summary Get books on sale
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBookOnSaleGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/book/onSale`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Fetches book\'s details from the database.
         * @summary Get book\'s details
         * @param {number} id ID of the book
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBookDetailsIdGet(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BookResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiBookDetailsIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiBookDetailsIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Fetches books on sale from the database.
         * @summary Get books on sale
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBookOnSaleGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<BookResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiBookOnSaleGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiBookOnSaleGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Fetches book\'s details from the database.
         * @summary Get book\'s details
         * @param {number} id ID of the book
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBookDetailsIdGet(id: number, options?: RawAxiosRequestConfig): AxiosPromise<BookResponse> {
            return localVarFp.apiBookDetailsIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Fetches books on sale from the database.
         * @summary Get books on sale
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBookOnSaleGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<BookResponse>> {
            return localVarFp.apiBookOnSaleGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Fetches book\'s details from the database.
     * @summary Get book\'s details
     * @param {number} id ID of the book
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiBookDetailsIdGet(id: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiBookDetailsIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Fetches books on sale from the database.
     * @summary Get books on sale
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiBookOnSaleGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiBookOnSaleGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UploadApi - axios parameter creator
 * @export
 */
export const UploadApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Uploads a single image file and returns its URL.
         * @summary Upload an image
         * @param {File} image The image file to upload
         * @param {number} bookId The ID of book to associate with the uploaded image
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUploadPost: async (image: File, bookId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'image' is not null or undefined
            assertParamExists('apiUploadPost', 'image', image)
            // verify required parameter 'bookId' is not null or undefined
            assertParamExists('apiUploadPost', 'bookId', bookId)
            const localVarPath = `/api/upload`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (image !== undefined) { 
                localVarFormParams.append('image', image as any);
            }
    
            if (bookId !== undefined) { 
                localVarFormParams.append('bookId', bookId as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UploadApi - functional programming interface
 * @export
 */
export const UploadApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UploadApiAxiosParamCreator(configuration)
    return {
        /**
         * Uploads a single image file and returns its URL.
         * @summary Upload an image
         * @param {File} image The image file to upload
         * @param {number} bookId The ID of book to associate with the uploaded image
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUploadPost(image: File, bookId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiUploadPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUploadPost(image, bookId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UploadApi.apiUploadPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UploadApi - factory interface
 * @export
 */
export const UploadApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UploadApiFp(configuration)
    return {
        /**
         * Uploads a single image file and returns its URL.
         * @summary Upload an image
         * @param {File} image The image file to upload
         * @param {number} bookId The ID of book to associate with the uploaded image
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUploadPost(image: File, bookId: number, options?: RawAxiosRequestConfig): AxiosPromise<ApiUploadPost200Response> {
            return localVarFp.apiUploadPost(image, bookId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UploadApi - object-oriented interface
 * @export
 * @class UploadApi
 * @extends {BaseAPI}
 */
export class UploadApi extends BaseAPI {
    /**
     * Uploads a single image file and returns its URL.
     * @summary Upload an image
     * @param {File} image The image file to upload
     * @param {number} bookId The ID of book to associate with the uploaded image
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UploadApi
     */
    public apiUploadPost(image: File, bookId: number, options?: RawAxiosRequestConfig) {
        return UploadApiFp(this.configuration).apiUploadPost(image, bookId, options).then((request) => request(this.axios, this.basePath));
    }
}



