/* tslint:disable */
/* eslint-disable */
/**
 * BookCycle API
 * API documentation for the BookCycle project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookResponse
 */
export interface BookResponse {
    /**
     * 
     * @type {string}
     * @memberof BookResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof BookResponse
     */
    author?: string;
    /**
     * 
     * @type {string}
     * @memberof BookResponse
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof BookResponse
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof BookResponse
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof BookResponse
     */
    discount?: number;
}

/**
 * Check if a given object implements the BookResponse interface.
 */
export function instanceOfBookResponse(value: object): value is BookResponse {
    return true;
}

export function BookResponseFromJSON(json: any): BookResponse {
    return BookResponseFromJSONTyped(json, false);
}

export function BookResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'author': json['author'] == null ? undefined : json['author'],
        'image': json['image'] == null ? undefined : json['image'],
        'description': json['description'] == null ? undefined : json['description'],
        'price': json['price'] == null ? undefined : json['price'],
        'discount': json['discount'] == null ? undefined : json['discount'],
    };
}

export function BookResponseToJSON(json: any): BookResponse {
    return BookResponseToJSONTyped(json, false);
}

export function BookResponseToJSONTyped(value?: BookResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'author': value['author'],
        'image': value['image'],
        'description': value['description'],
        'price': value['price'],
        'discount': value['discount'],
    };
}

