/* tslint:disable */
/* eslint-disable */
/**
 * BookCycle API
 * API documentation for the BookCycle project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BookResponse,
} from '../models/index';
import {
    BookResponseFromJSON,
    BookResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Fetches all books from the database.
     * Get all books
     */
    async apiBookAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BookResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/book/all`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BookResponseFromJSON));
    }

    /**
     * Fetches all books from the database.
     * Get all books
     */
    async apiBookAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BookResponse>> {
        const response = await this.apiBookAllGetRaw(initOverrides);
        return await response.value();
    }

}
